config/routes.rb
Rails.application.routes.draw do
  resources :projects
  get 'projects/:id/view_pdf' => 'projects#view_pdf', as: :view_pdf

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
  accepts_nested_attributes_for :tasks, :reject_if => :all_blank, :allow_destroy => true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :Project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.tasks.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def view_pdf
    @project = Project.find(params[:id])
    filename = @project.name.strip# + Time.now.to_s
    render  :pdf => filename  ,
            #:template => 'layouts/pdf.pdf.erb',    to render any partial/view >> if commented,function name view wud be called
            :layout => 'layouts/pdf.pdf.erb',
            :wkhtmltopdf => '/home/naumantahir/.rbenv/shims/wkhtmltopdf',
            :save_to_file => Rails.root.join('pdfs', "#{filename}.pdf")
            #save_only:                      false,                        # depends on :save_to_file being set first
    Pmail.send_email('nomibzu@gmail.com',filename).deliver
    #send_file '/path/to.zip'
    #attachments['filename.jpg'] = File.read('/path/to/filename.jpg')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, tasks_attributes: [:id, :name, :description, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CocoPDF</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/pdf.pdf.erb
<html>
<head></head>
<title>RailsWickedPdf
  <%= wicked_pdf_stylesheet_link_tag    "application", :media => "all" %>
  <%= wicked_pdf_javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</title>
<body>
<p>From LAout</p>
<%= yield %>
</body>
</html>

app/views/pmail/send_email.html.slim
html
    head
    body
        h1 Hi
        p Sample mail sent using smtp.

app/views/projects/_form.html.slim
= form_for(@project) do |f|
    -if @project.errors.any?
        #error_explanation
        h2
        |
        = pluralize(@project.errors.count, "error")
        | prohibited this project from being saved:

        ul
            -@project.errors.full_messages.each do |message|
            li= message

    .field
        = f.label :name
        br
        = f.text_field :name

    #tasks
        = f.fields_for :tasks do |t|
            = render 'projects/task_fields', f: t

        .links
            = link_to_add_association 'add task', f, :tasks, class: "btn btn-default"
        .actions
            = f.submit

app/views/projects/_task_fields.html.slim
.nested-fields
    = f.text_field :name
    = f.text_field :description
    = link_to_remove_association "Remove Task", f, class: "btn btn-default"

app/views/projects/edit.html.slim
h1 Editing Project

= render 'form'

= link_to 'Show', @project, class: "btn btn-default"
= link_to 'Back', projects_path, class: "btn btn-default"

app/views/projects/index.html.slim
p#notice = notice

h1 Listing Projects

table.table.table-condensed
    thead
        tr
            th Name

    tbody
    - @projects.each do |project|
        tr
            td= project.name
            td= link_to 'Show', project
            td= link_to 'Edit', edit_project_path(project)
            td= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }

= link_to 'New Project', new_project_path, class: "btn btn-default"

app/views/projects/new.html.slim
h1 New Project

= render 'form'

= link_to 'Back', projects_path, class: "btn btn-default"

app/views/projects/show.html.slim
p#notice= notice
h3= "Project Name: #{@project.name}"
strong Tasks:
- if @project.tasks.present?
    table.table
        thead
            tr
                th Name
                th Description
        tbody
            - @project.tasks.each do |t|
                tr
                    td= t.name
                    td= t.description

- else
    = "No tasks exist"

.pappu
    = link_to 'Print PDF', view_pdf_path(@project), data: {no_turbolink: true}, class: "btn btn-default"
    br
    = link_to 'Edit', edit_project_path(@project), class: "btn btn-default"
    span
    = link_to 'Back', projects_path, class: "btn btn-default"

app/views/projects/view_pdf.html.slim
.row
    = wicked_pdf_image_tag('header.jpg')

.row
    table.table
        thead
            th Name
        tbody
            tr
                td
                    = @project.name
    p ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse interdum semper placerat. Aenean mattis fringilla risus ut fermentum. Fusce posuere dictum venenatis. Aliquam id tincidunt ante, eu pretium eros. Sed eget risus a nisl aliquet scelerisque sit amet id nisi. Praesent porta molestie ipsum, ac commodo erat hendrerit nec. Nullam interdum ipsum a quam euismod, at consequat libero bibendum. Nam at nulla fermentum, congue lectus ut, pulvinar nisl. Curabitur consectetur quis libero id laoreet. Fusce dictum metus et orci pretium, vel imperdiet est viverra. Morbi vitae libero in tortor mattis commodo. Ut sodales libero erat, at gravida enim rhoncus ut.